### ISSUE TITLE
Will break in SMAPI 3.0

### ISSUE THREAD

**Issue by BatmanAMA** [KabigonFirst/StardewValleyMods#4]
[SMAPI] kisekae will break in the upcoming SMAPI 3.0 (EntryDll value with case-insensitive capitalisation is deprecated since SMAPI 2.11).
[SMAPI] kisekae will break in the upcoming SMAPI 3.0 (non-string manifest version is deprecated since SMAPI 2.8).

**Comment by KabigonFirst** [comment]
Updated by accetping Pathoschild's pull request.
